default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_dev

test:
  <<: *default
  database: your_app_name_test
